# 需要打上镜像tag,拉取centos 7的镜像
FROM java:8u20
MAINTAINER simeyg #把宿主机当前上下文的read.txt拷贝到容器/usr/local/路径下
COPY read.txt /usr/local/cincontainer.txt
#把java与tomcat添加到容器中
#ADD jdk-18_linux-x64_bin.tar.gz /usr/local/
#ADD apache-tomcat-10.0.23.tar.gz /usr/local/
#安装vim编辑器
RUN #yum -y install vim
#设置工作访问时候的WORKDIR路径，登录落脚点
ENV MYPATH /usr/local
WORKDIR $MYPATH
#配置java与tomcat环境变量
#ENV JAVA_HOME /usr/local/jdk-18.0.2.1
#ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
#ENV CATALINA_HOME /usr/local/apache-tomcat-10.0.23
#ENV CATALINA_BASE /usr/local/apache-tomcat-10.0.23
#ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/lib:$CATALINA_HOME/bin #容器运行时监听的端口
EXPOSE 8080
#启动时运行tomcat，以下3种启动方式任意选择一种，startup.sh底层也是调用了catalina.sh
# ENTRYPOINT ["/usr/local/apache-tomcat-10.0.23/bin/startup.sh" ]
# CMD ["/usr/local/apache-tomcat-10.0.23/bin/catalina.sh","run"]
CMD /usr/local/apache-tomcat-10.0.23/bin/startup.sh && tail -F /usr/local/apache-tomcat-10.0.23/logs/catalina.out