apiVersion: v1  #kubectl api-versions 可以通过这条指令去看版本信息
kind: Pod # 指定资源类别
metadata: #资源的一些元数据
  name: app3
  namespace: default
spec:
  containers:
    - name: k8s-spring-test2
      image: registry.cn-hangzhou.aliyuncs.com/simeyghub/k8s-spring-test:v10
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP